name: Windows EXE Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        shell: pwsh
        run: |
          $icon = "assets/streamq.ico"
          if (Test-Path $icon) { $iconArg = "--icon `"$icon`"" } else { $iconArg = "" }
          pyinstaller --noconfirm --clean --name "StreamQ" --windowed `
            $iconArg `
            --collect-all yt_dlp --collect-all ttkbootstrap `
            --collect-submodules pycryptodomex `
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: StreamQ-windows
          path: dist/StreamQ/**
